name: Meson CI

on:
    push:
        branches: ["main", "master"]
    pull_request:
    workflow_dispatch:

jobs:
    build:
        name: ${{ matrix.config.name }}
        runs-on: ${{ matrix.config.os }}

        strategy:
            fail-fast: false
            matrix:
                config:
                    - name: Windows MSVC
                      os: windows-latest
                      msvc: true
                      buildtype: release
                    - name: Windows MingGW
                      os: windows-latest
                      msvc: false
                      buildtype: release
                    - name: Linux GCC
                      os: ubuntu-22.04
                      buildtype: release
                      use-clang: false
                    - name: Linux Clang
                      os: ubuntu-22.04
                      buildtype: release
                      use-clang: true
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: "0"

            - name: Setup Meson
              run: |
                  python -m pip install --upgrade pip
                  pip install meson

            - name: Setup MSVC (Windows)
              if: matrix.config.os == 'windows-latest' && matrix.config.msvc == true
              uses: ilammy/msvc-dev-cmd@v1
              with:
                  vsversion: 2023

            - name: Setup MinGW (Windows)
              if: matrix.config.os == 'windows-latest' && matrix.config.msvc == false
              uses: egor-tensin/setup-mingw@v2
              with:
                  platform: x64
                  version: latest

            - name: Setup Clang (Linux)
              if: matrix.config.os == 'ubuntu-22.04' && matrix.config.use-clang == true
              uses: egor-tensin/setup-clang@v1
              with:
                  version: 17
                  platform: x64

            - name: Setup GCC (Linux)
              if: matrix.config.os == 'ubuntu-22.04' && matrix.config.use-clang == false
              uses: egor-tensin/setup-gcc@v1
              with:
                  version: 13
                  platform: x64

            - name: Install dependencies (Linux)
              if: matrix.config.os == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install ninja-build -y

            - name: Configure
              run: meson setup build -Dbuildtype=${{ matrix.config.buildtype }}

            - name: Build
              run: meson compile -C build
